version: '2'
services:
  exo:
    image: exoplatform/exo-community:4.4
    environment:
      EXO_PROXY_VHOST: localhost
      EXO_PROXY_PORT: 80
      EXO_DB_HOST: mysql
      EXO_PROXY_SSL: "false"
      EXO_DB_TYPE: mysql
      EXO_DB_NAME: exo
      EXO_DB_USER: exo
      EXO_DB_PASSWORD: my-secret-pw
      EXO_ADDONS_LIST: exo-jdbc-driver-mysql
      # EXO_ADDONS_LIST: exo-wiki-macro-loremipsum
    ports:
      - "8080:8080"
    volumes:
      - exo_data:/srv/exo
      - exo_logs:/var/log/exo
      - ./target/wiki-macro-loremipsum.jar:/opt/exo/lib/wiki-macro-loremipsum.jar:ro
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: my-super-secret-pw
      MYSQL_DATABASE: exo
      MYSQL_USER: exo
      MYSQL_PASSWORD: my-secret-pw
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  exo_data:
  exo_logs:
  mysql_data:
